server:
  port: 12345
spring:
  profiles:
    include:
      - mysql
      - security
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:db;MODE=MYSQL;
#    username: sa
#    password:



  data:
    redis:
      repositories:
        enabled: false

  cache:
    type: redis

  redis:
    host: 43.202.241.133
    port: 6379
    expire: 60


