spring:
  profiles:
    include: -mysql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      repositories:
        enabled: false

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379
    expire: 60

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

#spring:
#  profiles:
#    include: oauth
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:db;MODE=MYSQL;
#    username: sa
#    password:
