spring:
  profiles:
    include:
      - mysql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:db;MODE=MYSQL;
#    username: sa
#    password:

jwt:
  secret: "VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa"

