spring:
  profiles:
    include:
      - mysql
      - security
      - cloud
      - redis
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      repositories:
        enabled: false

  cache:
    type: redis


