server:
  port: 12345
spring:
  profiles:
    include:
      - mysql
      - security
      - cloud
      - redis
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:db;MODE=MYSQL;
#    username: sa
#    password:



  data:
    redis:
      repositories:
        enabled: false

  cache:
    type: redis



#  cloud:
#    aws:
#      credentials:
#        access-key: "123456"
#        secret-key: "123456"
#      region:
#        static: ap-northeast-2



#  cloud:
#    aws:
#      s3:
#        bucket: "my bucket"
#      stack.auto: false
#      region.static: ap-northeast-2
#      credentials:
#        access-Key: "123456"
#        secretKey: [ secret key ]


#  local mysql
  datasource:
    url: jdbc:mysql://localhost:3306/ufo
    username: root
    password: 12345


